UNDERSTAT_BASE_URL = "https://understat.com"

UNDERSTAT_STATS_DATA_URL = f"{UNDERSTAT_BASE_URL}/getStatData"
UNDERSTAT_LEAGUE_DATA_URL = f"{UNDERSTAT_BASE_URL}/getLeagueData/{{}}/{{}}"
UNDERSTAT_TEAM_DATA_URL = f"{UNDERSTAT_BASE_URL}/getTeamData/{{}}/{{}}"
UNDERSTAT_PLAYER_DATA_URL = f"{UNDERSTAT_BASE_URL}/getPlayerData/{{}}"
UNDERSTAT_MATCH_DATA_URL = f"{UNDERSTAT_BASE_URL}/getMatchData/{{}}"
UNDERSTAT_TEAM_PLAYER_STAT_URL = f"{UNDERSTAT_BASE_URL}/main/getPlayersStats/"
UNDERSTAT_PLAYERS_SEARCH_URL = f"{UNDERSTAT_BASE_URL}/main/getPlayersName/{{}}"
UNDERSTAT_PLAYER_MATCHES_URL = f"{UNDERSTAT_BASE_URL}/main/getPlayerMatches/{{}}"

UNDERSTAT_LEAGUE_PAGE_URL = f"{UNDERSTAT_BASE_URL}/league/{{}}/{{}}"
UNDERSTAT_TEAM_PAGE_URL = f"{UNDERSTAT_BASE_URL}/team/{{}}/{{}}"
UNDERSTAT_PLAYER_PAGE_URL = f"{UNDERSTAT_BASE_URL}/player/{{}}"
